apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config 
data:
  APP_COLOR: blue
  APP_MODE: prod
  DB_INSTANCE: postgresql-instance
  DB_NAME: postgres
  DB_USER: postgres
  DB_PASSWORD: password